SET foreign_key_checks=0;
TRUNCATE log_user;
TRUNCATE mas_agent;
TRUNCATE mas_city;
TRUNCATE mas_color;
TRUNCATE mas_country;
TRUNCATE mas_counts;
TRUNCATE mas_customer;
TRUNCATE mas_customercategory;
TRUNCATE mas_customer_x_address;
TRUNCATE mas_customer_x_category;
TRUNCATE mas_department;
TRUNCATE mas_designation;
TRUNCATE mas_employee;
TRUNCATE mas_employeecategory;
TRUNCATE mas_errorcode;
TRUNCATE mas_expensetype;
TRUNCATE mas_hours;
TRUNCATE mas_item;
TRUNCATE mas_itemgroup;
TRUNCATE mas_itemtype;
TRUNCATE mas_location;
TRUNCATE mas_machine;
TRUNCATE mas_native;
TRUNCATE mas_qualification;
TRUNCATE mas_routes;
TRUNCATE mas_skills;
TRUNCATE mas_state;
TRUNCATE mas_supplier;
TRUNCATE mas_suppliercategory;
TRUNCATE mas_suppliers_x_category;
TRUNCATE mas_tallyledger;
TRUNCATE mas_warehouse;
TRUNCATE mas_wastetype;
TRUNCATE trn_autoconer;
TRUNCATE trn_autoconerstopage;
TRUNCATE trn_blendingissue;
TRUNCATE trn_blendingissuedetail;
TRUNCATE trn_blendingpgmplan;
TRUNCATE trn_blendingpgmplandetail;
TRUNCATE trn_blendingreceipt;
TRUNCATE trn_blendingreceiptdetail;
TRUNCATE trn_blendingreturn;
TRUNCATE trn_blendingreturndetail;
TRUNCATE trn_carding;
TRUNCATE trn_comper;
TRUNCATE trn_cottoninward;
TRUNCATE trn_cottoninwarddetail;
TRUNCATE trn_creditnote;
TRUNCATE trn_creditnotedetail;
TRUNCATE trn_debitnote;
TRUNCATE trn_debitnotedetail;
TRUNCATE trn_deliverychallan;
TRUNCATE trn_deliverychallandetail;
TRUNCATE trn_drawing;
TRUNCATE trn_expensesentry;
TRUNCATE trn_genpurchaseinward;
TRUNCATE trn_genpurchaseinwarddetail;
TRUNCATE trn_jobworkreturn;
TRUNCATE trn_jobworkreturndetail;
TRUNCATE trn_mixingchart;
TRUNCATE trn_mixingchartdetail;
TRUNCATE trn_mixingissuedetail;
TRUNCATE trn_production;
TRUNCATE trn_productiondetail;
TRUNCATE trn_purchaseinward;
TRUNCATE trn_purchaseinwarddetail;
TRUNCATE trn_purchaseorder;
TRUNCATE trn_purchaseorderdetail;
TRUNCATE trn_sales;
TRUNCATE trn_salesdetail;
TRUNCATE trn_salesorder;
TRUNCATE trn_salesorderdetail;
TRUNCATE trn_simplex;
TRUNCATE trn_spinning;
TRUNCATE trn_spinningstopage;
TRUNCATE trn_spin_summary;
TRUNCATE trn_spin_summarydetail;
TRUNCATE trn_supplierpgmplan;
TRUNCATE trn_supplierpgmplandetail;
TRUNCATE trn_wastecottonreceipt;
TRUNCATE trn_wastecottonreceiptdetail;
TRUNCATE trn_yarnreceipt;
TRUNCATE trn_yarnreceiptdetail;
SET foreign_key_checks=1;

INSERT INTO `mas_country` (`CountryId`, `CountryName`, `IsActive`) VALUES (1, 'INDIA', 1);
INSERT INTO `mas_state` (`StateId`, `CountryId`, `StateName`, `StateCode`, `IsActive`) VALUES (1, 1, 'TAMILNADU', '33', 1);
INSERT INTO `mas_city` (`CityId`, `StateId`, `CityName`, `IsActive`) VALUES (1, 1, 'VEDACHENDUR', 1);
INSERT INTO `mas_customercategory` (`CustomerCategoryId`, `CustomerCategory`, `IsActive`) VALUES (1, 'Purchase', 1);
INSERT INTO `mas_employee` (`EmployeeId`, `EmpNo`, `Emp_Id`, `EmpName`, `EmpName_Tamil`, `FatherName_Tamil`, `DepartmentId`, `DesignationId`, `ShiftId`, `Wage_Day`, `Wage_Day_f`, `Address1`, `Address2`, `City`, `PinCode`, `StatusId`, `MobileNo`, `DoJ`, `DOr`, `Ot_Hr`, `Machine_Id`, `BasicPay`, `bSalary`, `Inc1`, `Inc2`, `Inc3`, `Inc4`, `Inc5`, `Inc6`, `IsIncApprove`, `PeSalary`, `EmployeeCategoryId`, `GenderId`, `Dob`, `IsInsert`, `IsDelete`, `IsUpdate`, `WeekDaysId`, `El_Op`, `Upto_W_Days`, `Spl_Allowance`, `Food_Allowance`, `Cug_Allowance`, `Other_Allowance`, `Mobile_Allowance`, `Other_Deduction`, `Pf_No`, `Esi_No`, `LocationId`, `SkillId`, `QualificationId`, `CityId`, `EmpImg`, `IsPE`, `IsMess`, `IsIncentive`, `IsPF`, `IsESI`, `IsIncentiveElig`, `NativeId`, `RouteId`, `BankName`, `BankAccNo`, `BankAccName`, `IfscCode`, `HoursId`, `AadharNo`, `PANNo`, `DrivingLicenceNo`) VALUES (1, 1, 1, 'SUPERVISOR', NULL, NULL, 0, 0, 0, 0.00, 0.00, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, 0.00, 0, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1, 0.00, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, NULL, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `mas_employeecategory` (`EmployeeCategoryId`, `EmployeeCategory`, `IsActive`) VALUES (1, 'WORKER', 1);
INSERT INTO `mas_employeecategory` (`EmployeeCategoryId`, `EmployeeCategory`, `IsActive`) VALUES (2, 'STAFF', 1);
INSERT INTO `mas_employeecategory` (`EmployeeCategoryId`, `EmployeeCategory`, `IsActive`) VALUES (3, 'SECURITY', 1);
INSERT INTO `mas_employeecategory` (`EmployeeCategoryId`, `EmployeeCategory`, `IsActive`) VALUES (5, 'STIPEND', 1);

